import { Injectable } from '@angular/core';
import { IProduct, ProductType } from 'app/types/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

    #products : IProduct[] = [

        // CashBox S NEW
        { 
          id: "292af756-288c-4942-a6f3-c7d69f889545", 
          name: 'CashBox S', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox S - New/CashBox S_front.png',
          menu:   'assets/menu/CashBox S_new_front.webp',
          banner: 'assets/banner_slider/CashBox S_new_front.webp',
          subheaderImage: 'assets/subheader/CashConcept-CashBox_S_new.webp',
          gallery: [
            { src: "assets/products/CashBox S - New/CashBox S_front.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_front.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S_side_face.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_side_face.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S_front_2.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_front_2.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S_side_face_2.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_side_face_2.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S_side_face_3.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_side_face_3.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S_top.png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S_top.png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S(1).png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S(1).png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S(2).png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S(2).png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S(3).png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S(3).png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S(4).png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S(4).png", isVideo: false },
            { src: "assets/products/CashBox S - New/CashBox S(5).png", thumbnail: "assets/products/CashBox S - New/thumbnails/CashBox S(5).png", isVideo: false },
            { src: "ScQVH8N6EhU", thumbnail: 'assets/products/CashBox S - New/thumbnails/ScQVH8N6EhU-def.jpg', isVideo: true },
            { src: "OteVrf55LC4", thumbnail: 'assets/products/CashBox S - New/thumbnails/OteVrf55LC4-def.jpg', isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox S - New/technical_features/fr/Fiche technique CashBox S.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox S - New/technical_features/en/Technical sheet  CashBox S.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox S - New/technical_features/nl/Technische gegevensbladen CashBox S.pdf"},
          ],
          isCompared: false,
          price: 5950,
          leasingPrice: 121.98,
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 1,
          nbTicket: 40,
          nbTicket2: 300,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 2,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: false,
          length: 29,
          depth: 36,
          height: 60,
          weight: 29
        },

        // CashBox S
        // { 
        //   id: "65648d9c-2896-48e8-a6fd-4a60b9627d78", 
        //   name: 'CashBox S', 
        //   type: ProductType.COIN_CHANGER,
        //   image:  'assets/products/CashBox S/CashBox S_front.png',
        //   menu:   'assets/menu/CashBox S_front.webp',
        //   banner: 'assets/banner_slider/CashBox S_front.webp',
        //   gallery: [
        //     { src: "assets/products/CashBox S/CashBox S_front.png", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_front.png", isVideo: false },
        //     { src: "assets/products/CashBox S/CashBox S_side_face.png", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_side_face.png", isVideo: false },
        //     { src: "assets/products/CashBox S/CashBox S_integrated.png", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_integrated.png", isVideo: false },
        //     { src: "assets/products/CashBox S/CashBox S_posed.jpeg", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_posed.png", isVideo: false },
        //     { src: "assets/products/CashBox S/CashBox S_posed_2.jpeg", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_posed_2.png", isVideo: false },
        //     { src: "assets/products/CashBox S/CashBox S_posed_3.jpeg", thumbnail: "assets/products/CashBox S/thumbnails/CashBox S_posed_3.png", isVideo: false },
        //   ],
        //   technicalFeatures: [
        //     {'languageCode': 'fr', 'path': "assets/products/CashBox S/technical_features/fr/Fiche technique CashBox S.pdf"},
        //     {'languageCode': 'en', 'path': "assets/products/CashBox S/technical_features/en/Technical sheet CashBox S.pdf"},
        //     {'languageCode': 'nl', 'path': "assets/products/CashBox S/technical_features/nl/Technische gegevensbladen CashBox S.pdf"},
        //   ],
        //   isCompared: false,
        //   price: 6400,
        //   leasingPrice: 131.20,
        //   acceptVerify: true,
        //   acceptBundle: false,
        //   redistributeAll: false,
        //   nbRedistribute: 3,
        //   typeOfTicket: "(5-10-20€)",
        //   recycler: true,
        //   nbRecycler: 1,
        //   nbTicket: 80,
        //   nbTicket2: 500,
        //   redistributeBundle: false,
        //   fakeMoney: true,
        //   nbDistributor: 1,
        //   shieldingMM: 2,
        //   transponder: false,
        //   laptop: true,
        //   inche: 15,
        //   screenTactical: true,
        //   screenTacticalInche: 10,
        //   calculator: true,
        //   application: true,
        //   os: true,
        //   twiceDimensions: false,
        //   length: 36.5,
        //   depth: 38,
        //   height: 55.8,
        //   weight: 35
        // },  

        // CashBox Mini
        // { 
        //   id: "292af756-288c-4942-a6f3-c7d69f889529", 
        //   name: 'CashBox Mini', 
        //   type: ProductType.COIN_CHANGER,
        //   image: 'assets/products/CashBox Mini/CashBox Mini_front.png',
        //   menu:   'assets/menu/CashBox Mini_front.webp',
        //   banner: 'assets/banner_slider/CashBox Mini_front.webp',
        //   gallery: [
        //     { src: "assets/products/CashBox Mini/CashBox Mini_front.png", thumbnail: "assets/products/CashBox Mini/thumbnails/CashBox Mini_front.webp", isVideo: false },
        //     { src: "assets/products/CashBox Mini/CashBox Mini_side_face.png", thumbnail: "assets/products/CashBox Mini/thumbnails/CashBox Mini_side_face.png", isVideo: false },
        //     { src: "assets/products/CashBox Mini/CashBox Mini_placed_on.jpg", thumbnail: "assets/products/CashBox Mini/thumbnails/CashBox Mini_placed_on.png", isVideo: false },
        //     { src: "assets/products/CashBox Mini/CashBox Mini_integrated_on.png", thumbnail: "assets/products/CashBox Mini/thumbnails/CashBox Mini_integrated_on.png", isVideo: false }
        //   ],
        //   technicalFeatures: [
        //     {'languageCode': 'fr', 'path': "assets/products/CashBox Mini/technical_features/fr/Fiche technique CashBox Mini.pdf"},
        //     {'languageCode': 'en', 'path': "assets/products/CashBox Mini/technical_features/en/Technical sheet  CashBox Mini.pdf"},
        //     {'languageCode': 'nl', 'path': "assets/products/CashBox Mini/technical_features/nl/Technische gegevensbladen CashBox Mini.pdf"},
        //   ],
        //   isCompared: false,
        //   price: 7500,
        //   leasingPrice: 153.75,
        //   acceptVerify: true,
        //   redistributeAll: false,
        //   nbRedistribute: 2,
        //   typeOfTicket: "(5-10€) (5-20€) (10-20€)",
        //   recycler: true,
        //   nbRecycler: 2,
        //   nbTicket: 30,
        //   nbTicket2: 300,
        //   fakeMoney: true,
        //   nbDistributor: 1,
        //   shieldingMM: 2,
        //   transponder: true,
        //   monitor: true,
        //   inche: 12,
        //   screen: true,
        //   screenInche: 7,
        //   calculator: true,
        //   application: true,
        //   os: true,
        //   twiceDimensions: false,
        //   length: 29,
        //   depth: 36,
        //   height: 60,
        //   weight: 29
        // },

        // CashBox 3
        { 
          id: "9c9172aa-d80e-4f84-a620-7dcf1c54e869", 
          name: 'CashBox 3',
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 3/CashBox 3_front.png',
          menu:   'assets/menu/CashBox 3_front.webp',
          banner: 'assets/banner_slider/CashBox 3_front.webp',
          subheaderImage: 'assets/subheader/CashConcept-CashBox_3.webp',
          gallery: [
            { src: "assets/products/CashBox 3/CashBox 3_front.png", thumbnail: "assets/products/CashBox 3/thumbnails/CashBox 3_front.png", isVideo: false },
            // { src: "assets/products/CashBox 3/CashBox 3_side_face.png", thumbnail: "assets/products/CashBox 3/thumbnails/CashBox 3_side_face.png", isVideo: false },
            { src: "assets/products/CashBox 3/front.png", thumbnail: "assets/products/CashBox 3/thumbnails/front.png", isVideo: false },
            { src: "assets/products/CashBox 3/side.png", thumbnail: "assets/products/CashBox 3/thumbnails/side.png", isVideo: false },
            { src: "assets/products/CashBox 3/left-side.png", thumbnail: "assets/products/CashBox 3/thumbnails/left-side.png", isVideo: false },
            { src: "assets/products/CashBox 3/right-side.png", thumbnail: "assets/products/CashBox 3/thumbnails/right-side.png", isVideo: false },
            { src: "assets/products/CashBox 3/CashBox 3_integrated_on.png", thumbnail: "assets/products/CashBox 3/thumbnails/CashBox 3_integrated_on.png", isVideo: false },
            { src: "assets/products/CashBox 3/CashBox-3_placed_on.png", thumbnail: "assets/products/CashBox 3/thumbnails/CashBox-3_placed_on.png", isVideo: false },
            { src: "assets/products/CashBox 3/CashBox-3_on_base.png", thumbnail: "assets/products/CashBox 3/thumbnails/CashBox-3_on_base.png", isVideo: false },
            { src: "O6BarHMLqbQ", thumbnail: 'assets/products/CashBox 3/thumbnails/O6BarHMLqbQ-def.jpg', isVideo: true },
            { src: "F1F7YN0BKFU", thumbnail: 'assets/products/CashBox 3/thumbnails/F1F7YN0BKFU-def.jpg', isVideo: true },
            { src: "lyJvjQT24HE", thumbnail: 'assets/products/CashBox 3/thumbnails/lyJvjQT24HE-def.jpg', isVideo: true },

          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 3/technical_features/fr/Fiche technique CashBox 3.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 3/technical_features/en/Technical sheet   CashBox 3.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 3/technical_features/nl/Technische gegevensbladen CashBox 3.pdf"},
          ],
          isCompared: false,
          price: 8250,
          leasingPrice: 169.13,
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 2,
          typeOfTicket: "(5-10€) (5-20€) (10-20€)",
          recycler: true,
          nbRecycler: 2,
          nbTicket: 100,
          nbTicket2: 400,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: false,
          length: 32.30,
          depth: 40.30,
          height: 58.50,
          weight: 60
        },

        // CashBox 5
        { 
          id: "597cb73c-6a8e-499e-8f5e-4fccb55879cc", 
          name: 'CashBox 5', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 5/CashBox 5_front.png',
          menu:   'assets/menu/CashBox 5_front.webp',
          banner: 'assets/banner_slider/CashBox 5_front.webp',
          subheaderImage: 'assets/subheader/CashConcept-CashBox_5.webp',
          gallery: [
            { src: "assets/products/CashBox 5/CashBox 5_front.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox 5_front.png", isVideo: false },
            // { src: "assets/products/CashBox 5/CashBox 5_side_face.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox 5_side_face.png", isVideo: false },
            { src: "assets/products/CashBox 5/front.png", thumbnail: "assets/products/CashBox 5/thumbnails/front.png", isVideo: false },
            { src: "assets/products/CashBox 5/side.png", thumbnail: "assets/products/CashBox 5/thumbnails/side.png", isVideo: false },
            { src: "assets/products/CashBox 5/left-side.png", thumbnail: "assets/products/CashBox 5/thumbnails/left-side.png", isVideo: false },
            { src: "assets/products/CashBox 5/right-side.png", thumbnail: "assets/products/CashBox 5/thumbnails/right-side.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox-5_placed_on.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox-5_placed_on.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox 5_integrated_on_2.jpeg", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox 5_integrated_on_2.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox-5_integrated_on_3.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox-5_integrated_on_3.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox-5_on_base_2.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox-5_on_base_2.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox-5_tamines.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox-5_tamines.png", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox 5_on_base.jpg", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox 5_on_base.jpg", isVideo: false },
            { src: "assets/products/CashBox 5/CashBox-5_placed_on_2.png", thumbnail: "assets/products/CashBox 5/thumbnails/CashBox-5_placed_on_2.png", isVideo: false },
            { src: "lOIKH3iI8WM", thumbnail: 'assets/products/CashBox 5/thumbnails/CashBox 5_Demo.png', isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 5/technical_features/fr/Fiche technique CashBox 5.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 5/technical_features/en/Technical sheet   CashBox 5.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 5/technical_features/nl/Technische gegevensbladen CashBox 5.pdf"},
          ],
          isCompared: false,
          price: 9550,
          leasingPrice: 195.78,
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 30,
          nbTicket2: 400,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: false,
          length: 32.30,
          depth: 40.30,
          height: 58.50,
          weight: 60
        },

        // CashBox 5+
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b9627d80", 
          name: 'CashBox 5+', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 5+/CashBox 5+_front.png',
          menu:   'assets/menu/CashBox 5+_front.webp',
          banner: 'assets/banner_slider/CashBox 5+_front.webp',
          subheaderImage: 'assets/subheader/CashConcept-CashBox_5+.webp',
          gallery: [
            { src: "assets/products/CashBox 5+/CashBox 5+_front.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_front.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_side_face.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_side_face.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_white.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_white.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_side_face_2.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_side_face_2.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_with_screen.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_with_screen.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_with_screen_2.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_with_screen_2.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_1.jpeg", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_1.jpeg", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_2.jpeg", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_2.jpeg", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_white_front.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_white_front.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_white_side_face.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_white_side_face.png", isVideo: false },
            { src: "assets/products/CashBox 5+/CashBox 5+_white_side_face_2.png", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_white_side_face_2.png", isVideo: false },
            { src: "8l8SfrE-vQ0", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_Demo.png", isVideo: true },
            { src: "e-iHd6oiSoU", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_Demo2.png", isVideo: true },
            { src: "Br9OsxCzfsA", thumbnail: "assets/products/CashBox 5+/thumbnails/CashBox 5+_Demo3.jpg", isVideo: true },
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 5+/technical_features/fr/Fiche technique CashBox 5+.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 5+/technical_features/en/Technical sheet CashBox 5+.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 5+/technical_features/nl/Technische gegevensbladen CashBox 5+.pdf"},
          ],
          isCompared: false,
          price: 9950,
          leasingPrice: 203.98,
          acceptVerify: true,
          acceptBundle: false,
          nbAccept: 0,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 30,
          nbTicket2: 400,
          redistributeBundle: false,
          nbRedistributeBundle: 0,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: false,
          length: 22.50,
          depth: 37.30,
          height: 140.30,
          coinLength: 0,
          coinDepth: 0,
          coinHeight: 0,
          weight: 75
        },

         // CashBox 6
        // { 
        //   id: "65648d9c-2896-48e8-a6fd-6420b9a45c1t", 
        //   name: 'CashBox 6', 
        //   type: ProductType.COIN_CHANGER,
        //   image: 'assets/products/CashBox 6/CashBox 6_front.png',
        //   menu:   'assets/menu/CashBox 6_front.webp',
        //   banner: 'assets/banner_slider/CashBox 6_front.webp',
        //   gallery: [
        //     { src: "assets/products/CashBox 6/CashBox 6_front.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_front.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_side_face.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_side_face.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_side_face_2.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_side_face_2.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_integrated.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_integrated.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_integrated_2.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_integrated_2.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_integrated_3.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_integrated_3.png", isVideo: false },
        //     { src: "assets/products/CashBox 6/CashBox 6_on_base.png", thumbnail: "assets/products/CashBox 6/thumbnails/CashBox 6_on_base.png", isVideo: false },
        //   ],
        //   technicalFeatures: [
        //     {'languageCode': 'fr', 'path': "assets/products/CashBox 6/technical_features/fr/Fiche technique CashBox 6.pdf"},
        //     {'languageCode': 'en', 'path': "assets/products/CashBox 6/technical_features/en/Technical sheet CashBox 6.pdf"},
        //     {'languageCode': 'nl', 'path': "assets/products/CashBox 6/technical_features/nl/Technische gegevensbladen CashBox 6.pdf"},
        //   ],
        //   isCompared: false,
        //   price: 11550,
        //   leasingPrice: 236.78,
        //   acceptVerify: true,
        //   acceptBundle: false,
        //   nbAccept: 0,
        //   redistributeAll: false,
        //   nbRedistribute: 4,
        //   typeOfTicket: "(5-10-20-50€)",
        //   recycler: true,
        //   nbRecycler: 4,
        //   nbTicket: 30,
        //   nbTicket2: 400,
        //   redistributeBundle: false,
        //   nbRedistributeBundle: 0,
        //   fakeMoney: true,
        //   nbDistributor: 1,
        //   shieldingMM: 4,
        //   transponder: true,
        //   monitor: true,
        //   inche: 12,
        //   screen: true,
        //   screenInche: 7,
        //   calculator: true,
        //   application: true,
        //   os: true,
        //   twiceDimensions: false,
        //   length: 46.60,
        //   depth: 32,
        //   height: 58.30,
        //   coinLength: 0,
        //   coinDepth: 0,
        //   coinHeight: 0,
        //   weight: 80
        // },

        // CashBox Pro
        { 
          id: "a91ecc97-f2a0-47e3-820a-7a91cf3f619a", 
          name: 'CashBox Pro', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox Pro/CashBox Pro_front.png', 
          menu:   'assets/menu/CashBox Pro_front.webp',
          banner: 'assets/banner_slider/CashBox Pro_front.webp', 
          subheaderImage: 'assets/subheader/CashConcept-CashBox_Pro.webp',
          isCompared: false,
          price: 12500,
          leasingPrice: 256.25,
          gallery: [
            { src: "assets/products/CashBox Pro/CashBox Pro_front.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_front.png", isVideo: false },
            { src: "assets/products/CashBox Pro/CashBox Pro_2.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_2.png", isVideo: false },
            { src: "assets/products/CashBox Pro/CashBox Pro_placed_on.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_placed_on.png", isVideo: false },
            { src: "assets/products/CashBox Pro/CashBox Pro_placed_on_2.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_placed_on_2.png", isVideo: false },
            { src: "assets/products/CashBox Pro/CashBox Pro_placed_on_4.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_placed_on_4.png", isVideo: false },
            { src: "assets/products/CashBox Pro/CashBox Pro_placed_on_5.png", thumbnail: "assets/products/CashBox Pro/thumbnails/CashBox Pro_placed_on_5.png", isVideo: false },
            { src: "Gwo3t2oQfko", thumbnail: "assets/products/CashBox Pro/thumbnails/Gwo3t2oQfko-def.jpg", isVideo: true },          
            { src: "wt1WQFbgw70", thumbnail: "assets/products/CashBox Pro/thumbnails/wt1WQFbgw70-def.jpg", isVideo: true },          
            { src: "eURq53twm0k", thumbnail: "assets/products/CashBox Pro/thumbnails/eURq53twm0k-def.jpg", isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox Pro/technical_features/fr/Fiche technique CashBox Pro.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox Pro/technical_features/en/Technical sheet   CashBox Pro.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox Pro/technical_features/nl/Technische gegevensbladen CashBox Pro.pdf"},
          ],
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 30,
          nbTicket2: 400,
          fakeMoney: true,
          nbDistributor: 8,
          shieldingMM: 4,
          monitor: true,
          inche: 12,
          transponder: true,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 22.70,
          ticketDepth: 60.50,
          ticketHeight: 29.50,
          coinLength: 30,
          coinDepth: 54.60,
          coinHeight: 33.60,
          weight: 92
        },

        // CashBox 7
        // { 
        //   id: "65648d9c-2896-48e8-a6fd-7820b9627b89", 
        //   name: 'CashBox 7', 
        //   type: ProductType.COIN_CHANGER,
        //   image: 'assets/products/CashBox 7/CashBox 7_front.png',
        //   menu:   'assets/menu/CashBox 7_front.webp',
        //   banner: 'assets/banner_slider/CashBox 7_front.webp',
        //   gallery: [
        //     { src: "assets/products/CashBox 7/CashBox 7_front.png", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_front.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_side_face.png", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_side_face.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_on_base.png", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_on_base.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_on_base_2.jpg", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_on_base_2.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_integrated_on.jpg", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_integrated_on.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_integrated_on_2.jpg", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_integrated_on_2.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_integrated_on_3.jpg", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_integrated_on_3.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_placed_on.jpg", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_placed_on.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_placed_on_2.png", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_placed_on_2.png", isVideo: false },
        //     { src: "assets/products/CashBox 7/CashBox 7_placed_on_3.png", thumbnail: "assets/products/CashBox 7/thumbnails/CashBox 7_placed_on_3.png", isVideo: false }
        //   ],
        //   technicalFeatures: [
        //     {'languageCode': 'fr', 'path': "assets/products/CashBox 7/technical_features/fr/Fiche technique CashBox 7.pdf"},
        //     {'languageCode': 'en', 'path': "assets/products/CashBox 7/technical_features/en/Technical sheet CashBox 7.pdf"},
        //     {'languageCode': 'nl', 'path': "assets/products/CashBox 7/technical_features/nl/Technische gegevensbladen CashBox 7.pdf"},
        //   ],
        //   isCompared: false,
        //   price: 13500,
        //   leasingPrice: 274.05,
        //   acceptVerify: true,
        //   acceptBundle: false,
        //   redistributeAll: false,
        //   nbRedistribute: 4,
        //   typeOfTicket: "(5-10-20-50€)",
        //   recycler: true,
        //   nbRecycler: 4,
        //   nbTicket: 45,
        //   nbTicket2: 600,
        //   redistributeBundle: true,
        //   nbRedistributeBundle: 15,
        //   fakeMoney: true,
        //   nbDistributor: 8,
        //   shieldingMM: 4,
        //   transponder: true,
        //   laptop: true,
        //   inche: 15,
        //   screenTactical: true,
        //   screenTacticalInche: 10,
        //   calculator: true,
        //   application: true,
        //   os: true,
        //   twiceDimensions: false,
        //   length: 56,
        //   depth: 46.50,
        //   height: 59.20,
        //   weight: 70
        // },

        // CashBox 7 - New
        { 
          id: "50a28d9c-2896-48e8-a6fd-7820b95t4d8n", 
          name: 'CashBox 7', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 7 - New/CashBox 7_front.png',
          menu:   'assets/menu/CashBox 7_new_front.webp',
          banner: 'assets/banner_slider/CashBox 7_new_front.webp',
          gallery: [
            { src: "assets/products/CashBox 7 - New/CashBox 7_front.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_front.png", isVideo: false },
            { src: "assets/products/CashBox 7 - New/CashBox 7_integrated.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_integrated.png", isVideo: false },
            { src: "assets/products/CashBox 7 - New/CashBox 7_integrated_2.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_integrated_2.png", isVideo: false },
            { src: "assets/products/CashBox 7 - New/CashBox 7_integrated_3.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_integrated_3.png", isVideo: false },
            { src: "assets/products/CashBox 7 - New/CashBox 7_on_base.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_on_base.png", isVideo: false },
            { src: "assets/products/CashBox 7 - New/CashBox 7_on_base_2.png", thumbnail: "assets/products/CashBox 7 - New/thumbnails/CashBox 7_on_base_2.png", isVideo: false },
            { src: "ITek2MqPCwQ", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo2.png", isVideo: true },
            { src: "dwpDV8J5O_4", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo3.png", isVideo: true },
            { src: "cj6zmmSC-ws", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo4.png", isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 7 - New/technical_features/fr/Fiche technique CashBox 7.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 7 - New/technical_features/en/Technical sheet CashBox 7.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 7 - New/technical_features/nl/Technische gegevensbladen CashBox 7.pdf"},
          ],
          isCompared: false,
          price: 13000,
          leasingPrice: 263.90,
          acceptVerify: true,
          acceptBundle: true,
          nbAccept: 50,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 60,
          nbTicket2: 1500,
          redistributeBundle: true,
          nbRedistributeBundle: 20,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 25.60,
          ticketDepth: 62,
          ticketHeight: 54.10,
          coinLength: 23.10,
          coinDepth: 37.70,
          coinHeight: 58,
          weight: 85
        },

        // CashBox 7+
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b9627f70", 
          name: 'CashBox 7+', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 7+/CashBox 7+_front.png',
          menu:   'assets/menu/CashBox 7+_front.webp',
          banner: 'assets/banner_slider/CashBox 7+_front.webp',
          subheaderImage: 'assets/subheader/CashConcept-CashBox_7+.webp',
          gallery: [
            { src: "assets/products/CashBox 7+/CashBox 7+_front.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_front.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_side_face.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_side_face.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_side_face_2.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_side_face_2.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_on_base_2.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_on_base_2.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_on_base.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_on_base.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_placed_on.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_placed_on.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_placed_on_2.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_placed_on_2.png", isVideo: false },
            { src: "assets/products/CashBox 7+/CashBox 7+_placed_on_3.png", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_placed_on_3.png", isVideo: false },
            { src: "tt6aRMaC5F8", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },
            { src: "ITek2MqPCwQ", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo2.png", isVideo: true },
            { src: "dwpDV8J5O_4", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo3.png", isVideo: true },
            { src: "cj6zmmSC-ws", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo4.png", isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 7+/technical_features/fr/Fiche technique CashBox 7+.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 7+/technical_features/en/Technical sheet   CashBox 7+.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 7+/technical_features/nl/Technische gegevensbladen CashBox 7+.pdf"},
          ],
          isCompared: false,
          price: 14990,
          leasingPrice: 304.30,
          acceptVerify: true,
          acceptBundle: true,
          nbAccept: 50,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 60,
          nbTicket2: 1500,
          redistributeBundle: true,
          nbRedistributeBundle: 20,
          fakeMoney: true,
          nbDistributor: 8,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 25.60,
          ticketDepth: 62,
          ticketHeight: 54.10,
          coinLength: 30,
          coinDepth: 54.60,
          coinHeight: 33.60,
          weight: 120
        },

        // CashBox 7+ vertical
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b962a4f2", 
          name: 'CashBox 7+ Vertical', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical.png',
          menu:   'assets/menu/CashBox 7+ Vertical.webp',
          banner: 'assets/banner_slider/CashBox 7+ Vertical.webp',
          gallery: [
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical.png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical.png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(1).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(1).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(5).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(5).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(3).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(3).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(2).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(2).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(4).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(4).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(6).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(6).png", isVideo: false },
            { src: "assets/products/CashBox 7+ Vertical/CashBox 7+ Vertical(7).png", thumbnail: "assets/products/CashBox 7+ Vertical/thumbnails/CashBox 7+ Vertical(7).png", isVideo: false },
            { src: "wRc6wosPGXM", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },          
            { src: "EYMXvUUKPFQ", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },          
            { src: "HscM2ZTSgdw", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },          
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 7+ Vertical/technical_features/fr/Fiche technique CashBox 7+ Vertical.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 7+ Vertical/technical_features/en/Technical sheet   CashBox 7 + Vertical.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 7+ Vertical/technical_features/nl/Technische gegevensbladen CashBox 7+ Vertical.pdf"},
          ],
          isCompared: false,
          price: 14990,
          leasingPrice: 314.45,
          acceptVerify: true,
          acceptBundle: true,
          nbAccept: 50,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 60,
          nbTicket2: 1500,
          redistributeBundle: true,
          nbRedistributeBundle: 20,
          fakeMoney: true,
          nbDistributor: 8,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 25.60,
          ticketDepth: 62,
          ticketHeight: 80.50,
          coinLength: 22.50,
          coinDepth: 55.60,
          coinHeight: 80.50,
          weight: 130
        },

        // CashBox 8
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b9627f10", 
          name: 'CashBox 8', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 8/CashBox 8_front.png',
          menu:   'assets/menu/CashBox 8_front.webp',
          banner: 'assets/banner_slider/CashBox 8_front.webp', 
          gallery: [
            { src: "assets/products/CashBox 8/CashBox 8_front.png", thumbnail: "assets/products/CashBox 8/thumbnails/CashBox 8.png", isVideo: false },
            { src: "assets/products/CashBox 8/CashBox 8_2.png", thumbnail: "assets/products/CashBox 8/thumbnails/CashBox 8_2.png", isVideo: false },
            { src: "assets/products/CashBox 8/CashBox 8_placed_on.png", thumbnail: "assets/products/CashBox 8/thumbnails/CashBox 8_placed_on.png", isVideo: false },
            { src: "assets/products/CashBox 8/CashBox 8_integrated.png", thumbnail: "assets/products/CashBox 8/thumbnails/CashBox 8_integrated.png", isVideo: false },     
            { src: "tt6aRMaC5F8", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },
            { src: "ITek2MqPCwQ", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo2.png", isVideo: true },
            { src: "dwpDV8J5O_4", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo3.png", isVideo: true },
            { src: "cj6zmmSC-ws", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo4.png", isVideo: true }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 8/technical_features/fr/Fiche technique CashBox 8.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 8/technical_features/en/Technical sheet   CashBox 8.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 8/technical_features/nl/Technische gegevensbladen CashBox 8.pdf"},
          ],
          isCompared: false,
          price: 16990,
          leasingPrice: 324.80,
          acceptVerify: true,
          acceptBundle: true,
          nbAccept: 50,
          redistributeAll: false,
          nbRedistribute: 6,
          typeOfTicket: "(5-10-20-50-100-200€)",
          recycler: true,
          nbRecycler: 6,
          nbTicket: 60,
          nbTicket2: 1500,
          redistributeBundle: true,
          nbRedistributeBundle: 20,
          fakeMoney: true,
          nbDistributor: 8,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 25.60,
          ticketDepth: 62, 
          ticketHeight: 65,
          coinLength: 30,
          coinDepth: 54.60,
          coinHeight: 33.60,
          weight: 130
        },

        // CashBox 8+
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b962a5d1", 
          name: 'CashBox 8+', 
          type: ProductType.COIN_CHANGER,
          image: 'assets/products/CashBox 8+/CashBox 8+_front.png',
          menu:   'assets/menu/CashBox 8+_front.webp',
          banner: 'assets/banner_slider/CashBox 8+_front.webp',
          gallery: [
            { src: "assets/products/CashBox 8+/CashBox 8+_front.png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+_front.png", isVideo: false },         
            { src: "assets/products/CashBox 8+/CashBox 8+_front(1).png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+_front(1).png", isVideo: false },         
            { src: "assets/products/CashBox 8+/CashBox 8+(2).png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+(2).png", isVideo: false },         
            { src: "assets/products/CashBox 8+/CashBox 8+(3).png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+(3).png", isVideo: false },        
            { src: "assets/products/CashBox 8+/CashBox 8+_install.png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+_install.png", isVideo: false },         
            { src: "assets/products/CashBox 8+/CashBox 8+_install(2).png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+_install(2).png", isVideo: false },         
            { src: "assets/products/CashBox 8+/CashBox 8+_install(3).png", thumbnail: "assets/products/CashBox 8+/thumbnails/CashBox 8+_install(3).png", isVideo: false },         
            { src: "wRc6wosPGXM", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },          
            { src: "EYMXvUUKPFQ", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },          
            { src: "HscM2ZTSgdw", thumbnail: "assets/products/CashBox 7+/thumbnails/CashBox 7+_Demo.png", isVideo: true },
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox 8+/technical_features/fr/Fiche technique CashBox 8+.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox 8+/technical_features/en/Technical sheet   CashBox 8+.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox 8+/technical_features/nl/Technische gegevensbladen CashBox 8+.pdf"},
          ],
          isCompared: false,
          price: 14990,
          leasingPrice: 334.75,
          acceptVerify: true,
          acceptBundle: true,
          nbAccept: 50,
          redistributeAll: false,
          nbRedistribute: 6,
          typeOfTicket: "(5-10-20-50-100-200€)",
          recycler: true,
          nbRecycler: 6,
          nbTicket: 60,
          nbTicket2: 1500,
          redistributeBundle: true,
          nbRedistributeBundle: 20,
          fakeMoney: true,
          nbDistributor: 8,
          shieldingMM: 4,
          transponder: true,
          monitor: true,
          inche: 12,
          screen: true,
          screenInche: 7,
          calculator: true,
          application: true,
          os: true,
          twiceDimensions: true,
          ticketLength: 25.60,
          ticketDepth: 62,
          ticketHeight: 80.50,
          coinLength: 22.50,
          coinDepth: 55.60,
          coinHeight: 80.50,
          weight: 140
        },
        
        // CashBox Order 2
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b9627f4z", 
          name: 'CashBox Order 2', 
          type: ProductType.CONTROL_TERMINAL,
          image: 'assets/products/CashBox Order 2-4/CashBox Order 2.png',
          menu:   'assets/menu/CashBox Order 2.webp',
          banner: 'assets/banner_slider/CashBox Order 2.webp',
          subheaderImage: 'assets/subheader/Banière CashBox Order 2.webp',
          gallery: [
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 2.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 2.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 2_2.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 2_2.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 2_3.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 2_3.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 2 (1).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 2 (1).png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 2 (2).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 2 (2).png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 2 (3).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 2 (3).png', isVideo: false }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox Order 2-4/technical_features/fr/Fiche technique CashBox Order 2 CashConcept.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox Order 2-4/technical_features/en/Technical sheet  CashBox Order 2.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox Order 2-4/technical_features/nl/Technische gegevensbladen CashBox Order 2.pdf"},
          ],    
          isCompared: false,
          price: 11500,
          leasingPrice: 203.98,
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 2,
          typeOfTicket: "(5-10€) (5-20€) (10-20€)",
          recycler: true,
          nbRecycler: 2,
          nbTicket: 100,
          nbTicket2: 400,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 2.5,
          screenTactical: true,
          screenTacticalInche: 27,
          program: true,
          printer: true,
          application: true,
          leds: true,
          os: true,
          twiceDimensions: false,
          length: 42,
          depth: 40.20,
          height: 183,
          weight: 100
        },

        // CashBox Order 4
        { 
          id: "65648d9c-2896-48e8-a6fd-7820b9627f7a", 
          name: 'CashBox Order 4', 
          type: ProductType.CONTROL_TERMINAL,
          image: 'assets/products/CashBox Order 2-4/CashBox Order 4.png',
          menu:   'assets/menu/CashBox Order 4.webp',
          banner: 'assets/banner_slider/CashBox Order 4.webp',
          subheaderImage: 'assets/subheader/Banière CashBox Order 4.webp',
          gallery: [
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 4.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 4.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 2_2.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 2_2.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox Order 2_3.png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox Order 2_3.png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 4 (1).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 4 (1).png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 4 (2).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 4 (2).png', isVideo: false },
            { src: 'assets/products/CashBox Order 2-4/CashBox order 4 (3).png', thumbnail: 'assets/products/CashBox Order 2-4/thumbnails/CashBox order 4 (3).png', isVideo: false }
          ],
          technicalFeatures: [
            {'languageCode': 'fr', 'path': "assets/products/CashBox Order 2-4/technical_features/fr/Fiche technique CashBox Order 4 CashConcept.pdf"},
            {'languageCode': 'en', 'path': "assets/products/CashBox Order 2-4/technical_features/en/Technical sheet   CashBox Order 4 cash-pro.pdf"},
            {'languageCode': 'nl', 'path': "assets/products/CashBox Order 2-4/technical_features/nl/Technische gegevensbladen CashBox Order 4.pdf"},
          ],           
          isCompared: false,
          price: 13000,
          leasingPrice: 234.73,
          acceptVerify: true,
          redistributeAll: false,
          nbRedistribute: 4,
          typeOfTicket: "(5-10-20-50€)",
          recycler: true,
          nbRecycler: 4,
          nbTicket: 30,
          nbTicket2: 400,
          fakeMoney: true,
          nbDistributor: 1,
          shieldingMM: 2.5,
          screen: true,
          screenInche: 27,
          program: true,
          printer: true,
          application: true,
          leds: true,
          os: true,
          twiceDimensions: false,
          length: 42.50,
          depth: 40.20,
          height: 183,
          weight: 100
        }
    ];

  constructor() { }

  getProducts(type?: ProductType) : IProduct[] {
    if (type) {
      return this.#products.filter(product => product.type === type);
    }
    else {
      return this.#products;
    }
  }

  getProductById(id: string): IProduct | undefined {
    return this.#products.find(product => product.id === id);
  }
}
